<a href="https://colab.research.google.com/github/vinisilvacar/scripts_engenharia_dados/blob/main/ClassificacaoConcurso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tabula-py

Requirement already satisfied: tabula-py in /usr/local/lib/python3.10/dist-packages (2.10.0)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.26.4)
Requirement already satisfied: distro in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)

In [ ]:
import pandas as pd
import tabula

#Tratamento de Dados com as Notas Discursivas

## Tratamentos da primeira Tabela

In [ ]:
tabela_inteira_1 = tabula.read_pdf("resultadoObjetiva.pdf", pages="4")

df_tabela_01 = pd.DataFrame(tabela_inteira_1[0])
df_tabela_01 = df_tabela_01[4:] # Remove as 4 primeiras linhas de cada tabela
df_tabela_01 = df_tabela_01.dropna(axis=1, how='all')
df_tabela_01

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Nota Preliminar Pontuação preliminar nos Parâmetros Resultado preliminar nos,Unnamed: 5,Unnamed: 6
4,0338110030,VENANCIO HENRIQUE DA SILVA,101,Advogado,"1,00 1,50 1,00 0,50 1,36 8 25 2,50 1,00 1,00 2...","11,86",Aprovado
5,0338133616,VICTOR MINERVINO QUINTIERE,101,Advogado,"0,50 1,50 1,00 1,00 0,80 18 30 2,50 0,50 0,50 ...","9,80",Eliminado. Item 11.2 .17.
6,0338113763,VINICIUS CUNHA E SILVA,101,Advogado,"1,50 1,50 1,50 1,50 1,00 15 30 3,00 0,50 0,50 ...","13,00",Aprovado
7,0338111127,VINICIUS LOPES ALVES VIEIRA,101,Advogado,"1,00 1,50 1,00 2,00 0,55 21 29 2,50 0,50 0,50 ...","12,05",Aprovado
8,0338109487,VINNY SOUSA DE QUEIROZ,101,Advogado,"1,50 1,50 1,50 1,00 1,20 12 30 3,00 1,00 0,50 ...","13,70",Aprovado
9,0338113206,VITOR NEVES PALMEIRA,101,Advogado,"1,50 1,50 1,50 2,00 1,86 2 29 2,00 0,50 0,50 2...","13,36",Aprovado
10,0338122137,ADALBERTO ROLIM NOGUEIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,47 8 30 2,50 3,40 2,50 -...","15,87",Aprovado
11,0338126901,ALANE SERPA AMARAL,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,50 7 28 1,80 1,90 2,00 -...","12,70",Aprovado
12,0338102604,ALDERIAN GOMES DE GOIS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,17 12 29 1,00 2,80 1,50 ...","12,47",Aprovado
13,0338114429,ALEX DE OLIVEIRA MEIRELES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,54 6 26 2,00 1,50 2,00 -...","12,54",Aprovado
14,0338132128,ALEX FRANCO OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,00 1,00 15 30 3,00 1,90 2,70 ...","15,10",Aprovado
15,0338128018,ALINE PEREIRA CASCIANO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,60 6 30 2,50 3,40 3,00 -...","16,50",Aprovado
16,0338111684,ALLAN AMANCIO MOREIRA SILVA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,00 1,77 3 26 2,70 2,20 1,00 -...","14,17",Aprovado
17,0338100330,ALLAN TIMO GOMES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,50 6 24 1,50 0,00 2,00 -...","10,50",Aprovado
18,0338118214,ANDRE LUIZ PEREIRA VALENTIM,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 1,04 12 25 2,00 1,00 1,00 ...","11,04",Aprovado
19,0338113083,ANGELO BRUNO PEREIRA DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 2,00 1,67 5 30 1,50 2,00 2,00 -...","14,67",Aprovado
20,0338112656,ARNALDO LOPES DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,04 11 23 0,50 1,40 0,30 ...","8,74",Eliminado. Item 11.2 .17.
21,0338126382,ARNALDO SALES DE LIMA FILHO,102,Analista de Tecnologia da Informação,"1,00 1,00 1,50 0,50 1,33 7 21 2,00 1,20 0,00 -...","8,53",Eliminado. Item 11.2 .17.
22,0338129579,ARTHUR DE MELO GARCIA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,26 10 27 0,50 1,60 1,00 ...","9,86",Eliminado. Item 11.2 .17.
23,0338110322,BRENO RODRIGUES CARDOSO DE MOURA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,00 15 30 2,50 2,20 0,50 ...","12,20",Aprovado
24,0338103813,BRUNO ALVES DE SOUZA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,43 8 28 2,50 2,20 3,00 -...","16,13",Aprovado
25,0338122868,BRUNO DE SOUZA FERREIRA CARNEIRO,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
26,0338110902,BRUNO HENRIQUE SANTOS NASCIMENTO BENEVIDES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 1,92 1 24 0,30 1,00 2,00 -...","10,22",Aprovado
27,0338123583,BRUNO HENRIQUE SOUSA DO VAL,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,27 11 30 2,50 2,20 2,00 ...","14,97",Aprovado
28,0338133114,CARLOS ALBERTO DE AMORIM VIANA,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,45 8 29 2,50 1,50 1,00 -...","11,95",Aprovado
29,0338102354,CARLOS ANDRE ROCHA DA COSTA,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 23 0,00 0,00 0,00 -...","0,00",Eliminado. Item 11.2 .10.
30,0338124446,CARLOS RIBEIRO DA SILVA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,53 7 30 3,00 3,40 2,00 -...","16,93",Aprovado
31,0338107092,CECILIA MARGARETE HEINEN,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,52 6 25 2,00 2,20 2,00 -...","13,72",Aprovado
32,0338123476,CLEI ROBERTO NOGUEIRA DE OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,60 6 30 1,50 0,00 1,50 -...","11,10",Aprovado
33,0338117383,DANIEL DE ANDRADE CUNHA,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 1,00 2,00 0 24 1,70 4,00 3,00 -...","17,70",Aprovado
34,0338118231,DAVI SALES BARCELOS,102,Analista de Tecnologia da Informação,"1,50 2,00 1,50 1,50 1,84 2 25 0,70 0,00 2,00 -...","11,04",Aprovado
35,0338110733,DAVISON DA SILVA FERREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,73 4 30 1,00 1,00 1,00 -...","11,23",Aprovado
36,0338105388,DENYS ABNER SANTOS BEZERRA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,50 1,65 4 23 1,20 0,80 2,00 -...","11,65",Aprovado
37,0338122053,DHIOGO ANTONIO ALVES FERREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,28 9 25 1,70 2,00 1,00 -...","11,98",Aprovado
38,0338101433,DIEGO PEREIRA DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,54 6 26 1,20 0,60 2,00 -...","11,84",Aprovado
39,0338113295,DIEGO SOUZA SILVA ALMEIDA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,76 3 25 1,50 1,50 1,00 -...","11,76",Aprovado
40,0338102133,DIOGO MODRACH,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 1,52 5 21 0,20 0,00 0,00 -...","6,72",Eliminado. Item 11.2 .17.
41,0338127941,DIOGO SILVA DE CARVALHO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 2,00 0 28 2,70 4,00 2,50 -...","17,20",Aprovado
42,0338133640,EDERSON SZULCZEWSKI,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,67 5 30 1,50 2,20 1,50 -...","12,87",Aprovado
43,0338130607,ELIVAM DE SOUSA MARTINS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 1,27 11 30 2,00 0,00 2,00 ...","11,27",Aprovado
44,0338100391,ELVIS CASTRO TAVARES DA SILVA,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 1,00 1,15 11 26 3,00 3,40 3,00 ...","17,55",Aprovado
45,0338118652,ESDRAS LUCAS RAMOS MARTINS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,50 7 28 2,00 3,10 1,00 -...","13,10",Aprovado
46,0338134085,ESTEVAM GALVAO ALBUQUERQUE,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,73 4 30 2,50 3,40 2,00 -...","16,13",Aprovado
47,0338126793,ETTORE NOBREGA CHASE SILVA,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
48,0338120004,FELIPE ALVES LUTZ PINHEIRO,102,Analista de Tecnologia da Informação,"1,00 1,50 1,00 1,00 0,17 22 24 0,80 2,20 1,00 ...","8,67",Eliminado. Item 11.2 .17.
49,0338111755,FELIPE FREITAS SOARES,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,73 4 30 3,00 4,00 2,00 -...","17,73",Aprovado
50,0338100966,FERNANDO AUGUSTO DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,85 2 27 1,00 2,80 2,00 -...","13,65",Aprovado
51,0338128711,FERNANDO MOREIRA DE SOUZA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,43 8 28 1,20 1,60 1,50 -...","12,23",Aprovado
52,0338111911,FERNANDO TAVARES MACIEL AQUINO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,91 1 22 1,50 2,20 2,00 -...","13,11",Aprovado

In [ ]:
col_names = ['Num de inscrição', 'Nome Candidato', 'Vaga', 'Cargo', 'Notas', 'NPD', 'Situação']
df_resposta_tab_01 = pd.DataFrame(columns=col_names)

df_resposta_tab_01['Num de inscrição'] = df_tabela_01['Unnamed: 0']
df_resposta_tab_01['Nome Candidato'] = df_tabela_01['Unnamed: 1']
df_resposta_tab_01['Vaga'] = df_tabela_01['Unnamed: 2']
df_resposta_tab_01['Cargo'] = df_tabela_01['Unnamed: 3']
df_resposta_tab_01['Notas'] = df_tabela_01['Nota Preliminar Pontuação preliminar nos Parâmetros Resultado preliminar nos']
df_resposta_tab_01['NPD'] = df_tabela_01['Unnamed: 5']
df_resposta_tab_01['Situação'] = df_tabela_01['Unnamed: 6']

# Display the new DataFrame
df_resposta_tab_01

,Num de inscrição,Nome Candidato,Vaga,Cargo,Notas,NPD,Situação
4,0338110030,VENANCIO HENRIQUE DA SILVA,101,Advogado,"1,00 1,50 1,00 0,50 1,36 8 25 2,50 1,00 1,00 2...","11,86",Aprovado
5,0338133616,VICTOR MINERVINO QUINTIERE,101,Advogado,"0,50 1,50 1,00 1,00 0,80 18 30 2,50 0,50 0,50 ...","9,80",Eliminado. Item 11.2 .17.
6,0338113763,VINICIUS CUNHA E SILVA,101,Advogado,"1,50 1,50 1,50 1,50 1,00 15 30 3,00 0,50 0,50 ...","13,00",Aprovado
7,0338111127,VINICIUS LOPES ALVES VIEIRA,101,Advogado,"1,00 1,50 1,00 2,00 0,55 21 29 2,50 0,50 0,50 ...","12,05",Aprovado
8,0338109487,VINNY SOUSA DE QUEIROZ,101,Advogado,"1,50 1,50 1,50 1,00 1,20 12 30 3,00 1,00 0,50 ...","13,70",Aprovado
9,0338113206,VITOR NEVES PALMEIRA,101,Advogado,"1,50 1,50 1,50 2,00 1,86 2 29 2,00 0,50 0,50 2...","13,36",Aprovado
10,0338122137,ADALBERTO ROLIM NOGUEIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,47 8 30 2,50 3,40 2,50 -...","15,87",Aprovado
11,0338126901,ALANE SERPA AMARAL,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,50 7 28 1,80 1,90 2,00 -...","12,70",Aprovado
12,0338102604,ALDERIAN GOMES DE GOIS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,17 12 29 1,00 2,80 1,50 ...","12,47",Aprovado
13,0338114429,ALEX DE OLIVEIRA MEIRELES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,54 6 26 2,00 1,50 2,00 -...","12,54",Aprovado
14,0338132128,ALEX FRANCO OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,00 1,00 15 30 3,00 1,90 2,70 ...","15,10",Aprovado
15,0338128018,ALINE PEREIRA CASCIANO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,60 6 30 2,50 3,40 3,00 -...","16,50",Aprovado
16,0338111684,ALLAN AMANCIO MOREIRA SILVA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,00 1,77 3 26 2,70 2,20 1,00 -...","14,17",Aprovado
17,0338100330,ALLAN TIMO GOMES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,50 6 24 1,50 0,00 2,00 -...","10,50",Aprovado
18,0338118214,ANDRE LUIZ PEREIRA VALENTIM,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 1,04 12 25 2,00 1,00 1,00 ...","11,04",Aprovado
19,0338113083,ANGELO BRUNO PEREIRA DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 2,00 1,67 5 30 1,50 2,00 2,00 -...","14,67",Aprovado
20,0338112656,ARNALDO LOPES DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,04 11 23 0,50 1,40 0,30 ...","8,74",Eliminado. Item 11.2 .17.
21,0338126382,ARNALDO SALES DE LIMA FILHO,102,Analista de Tecnologia da Informação,"1,00 1,00 1,50 0,50 1,33 7 21 2,00 1,20 0,00 -...","8,53",Eliminado. Item 11.2 .17.
22,0338129579,ARTHUR DE MELO GARCIA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,26 10 27 0,50 1,60 1,00 ...","9,86",Eliminado. Item 11.2 .17.
23,0338110322,BRENO RODRIGUES CARDOSO DE MOURA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,00 15 30 2,50 2,20 0,50 ...","12,20",Aprovado
24,0338103813,BRUNO ALVES DE SOUZA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,43 8 28 2,50 2,20 3,00 -...","16,13",Aprovado
25,0338122868,BRUNO DE SOUZA FERREIRA CARNEIRO,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
26,0338110902,BRUNO HENRIQUE SANTOS NASCIMENTO BENEVIDES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 1,92 1 24 0,30 1,00 2,00 -...","10,22",Aprovado
27,0338123583,BRUNO HENRIQUE SOUSA DO VAL,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,27 11 30 2,50 2,20 2,00 ...","14,97",Aprovado
28,0338133114,CARLOS ALBERTO DE AMORIM VIANA,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,45 8 29 2,50 1,50 1,00 -...","11,95",Aprovado
29,0338102354,CARLOS ANDRE ROCHA DA COSTA,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 23 0,00 0,00 0,00 -...","0,00",Eliminado. Item 11.2 .10.
30,0338124446,CARLOS RIBEIRO DA SILVA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,53 7 30 3,00 3,40 2,00 -...","16,93",Aprovado
31,0338107092,CECILIA MARGARETE HEINEN,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,52 6 25 2,00 2,20 2,00 -...","13,72",Aprovado
32,0338123476,CLEI ROBERTO NOGUEIRA DE OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,60 6 30 1,50 0,00 1,50 -...","11,10",Aprovado
33,0338117383,DANIEL DE ANDRADE CUNHA,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 1,00 2,00 0 24 1,70 4,00 3,00 -...","17,70",Aprovado
34,0338118231,DAVI SALES BARCELOS,102,Analista de Tecnologia da Informação,"1,50 2,00 1,50 1,50 1,84 2 25 0,70 0,00 2,00 -...","11,04",Aprovado
35,0338110733,DAVISON DA SILVA FERREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,73 4 30 1,00 1,00 1,00 -...","11,23",Aprovado
36,0338105388,DENYS ABNER SANTOS BEZERRA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,50 1,65 4 23 1,20 0,80 2,00 -...","11,65",Aprovado
37,0338122053,DHIOGO ANTONIO ALVES FERREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,28 9 25 1,70 2,00 1,00 -...","11,98",Aprovado
38,0338101433,DIEGO PEREIRA DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,54 6 26 1,20 0,60 2,00 -...","11,84",Aprovado
39,0338113295,DIEGO SOUZA SILVA ALMEIDA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,76 3 25 1,50 1,50 1,00 -...","11,76",Aprovado
40,0338102133,DIOGO MODRACH,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 1,52 5 21 0,20 0,00 0,00 -...","6,72",Eliminado. Item 11.2 .17.
41,0338127941,DIOGO SILVA DE CARVALHO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 2,00 0 28 2,70 4,00 2,50 -...","17,20",Aprovado
42,0338133640,EDERSON SZULCZEWSKI,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,67 5 30 1,50 2,20 1,50 -...","12,87",Aprovado
43,0338130607,ELIVAM DE SOUSA MARTINS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 1,27 11 30 2,00 0,00 2,00 ...","11,27",Aprovado
44,0338100391,ELVIS CASTRO TAVARES DA SILVA,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 1,00 1,15 11 26 3,00 3,40 3,00 ...","17,55",Aprovado
45,0338118652,ESDRAS LUCAS RAMOS MARTINS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,50 7 28 2,00 3,10 1,00 -...","13,10",Aprovado
46,0338134085,ESTEVAM GALVAO ALBUQUERQUE,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,73 4 30 2,50 3,40 2,00 -...","16,13",Aprovado
47,0338126793,ETTORE NOBREGA CHASE SILVA,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
48,0338120004,FELIPE ALVES LUTZ PINHEIRO,102,Analista de Tecnologia da Informação,"1,00 1,50 1,00 1,00 0,17 22 24 0,80 2,20 1,00 ...","8,67",Eliminado. Item 11.2 .17.
49,0338111755,FELIPE FREITAS SOARES,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,73 4 30 3,00 4,00 2,00 -...","17,73",Aprovado
50,0338100966,FERNANDO AUGUSTO DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,85 2 27 1,00 2,80 2,00 -...","13,65",Aprovado
51,0338128711,FERNANDO MOREIRA DE SOUZA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,43 8 28 1,20 1,60 1,50 -...","12,23",Aprovado
52,0338111911,FERNANDO TAVARES MACIEL AQUINO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,91 1 22 1,50 2,20 2,00 -...","13,11",Aprovado

## Tratamento da segunda tabela

In [ ]:
tabela_inteira_2 = tabula.read_pdf("resultadoObjetiva.pdf", pages="5")

df_tabela_02 = pd.DataFrame(tabela_inteira_2[0])
df_tabela_02 = df_tabela_02[4:] # Remove as 4 primeiras linhas de cada tabela
df_tabela_02 = df_tabela_02.dropna(axis=1, how='all')
df_tabela_02

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Nota Preliminar Pontuação preliminar nos Parâmetros Resultado preliminar nos,Unnamed: 4,Unnamed: 5
4,0338123128,FERNANDO VINICIUS GONCALVES DE SOUZA,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
5,0338119704,FILIPE BARBOSA LIMA,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 2,00 0,67 20 30 1,50 2,80 3,00 ...","15,97",Aprovado
6,0338101937,FILIPE FERNANDES DE OLIVEIRA NASCIMENTO,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,23 10 26 1,50 2,50 2,00 ...","12,73",Aprovado
7,0338124136,FILIPE GUIMARAES DE OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 1,64 5 28 1,50 0,90 2,00 -...","11,04",Aprovado
8,0338105407,FRANCISCO ALISSON COSTA LOPES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,46 7 26 2,00 1,00 3,00 -...","13,96",Aprovado
9,0338103222,FRED ULISSES MARANHAO,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,77 3 26 1,50 4,00 1,00 -...","13,77",Aprovado
10,0338132606,GABRIEL HELENO GONCALVES DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,73 4 30 2,00 2,20 1,50 -...","13,93",Aprovado
11,0338121740,GABRIEL MENDONCA FERNANDES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 1,42 7 24 1,50 0,60 1,00 -...","10,52",Aprovado
12,0338106751,GABRIEL MOTA DA CAMARA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,57 6 28 2,50 1,60 2,50 -...","14,67",Aprovado
13,0338127224,GEDAIAS ELOI BRANDAO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,27 11 30 3,00 0,60 3,00 ...","13,87",Aprovado
14,0338113173,GIOVANNI CUNHA DE AMORIM,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,70 4 27 2,00 1,00 2,00 -...","12,70",Aprovado
15,0338118047,GUILHERME DE SOUZA PEREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,65 4 23 1,50 2,20 0,50 -...","11,85",Aprovado
16,0338131306,GUILHERME PASSOS CAMPOS,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
17,0338108957,GUSTAVO HENRIQUE ALVES RODRIGUES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,60 6 30 1,00 2,20 2,50 -...","13,30",Aprovado
18,0338121253,HENRIQUE PEREIRA DE FREITAS FILHO,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,53 7 30 1,80 4,00 2,00 -...","14,83",Aprovado
19,0338109956,IALA PATRICIA DE JESUS MONTEIRO DE JESUS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,67 5 30 3,00 0,60 2,00 -...","13,27",Aprovado
20,0338115090,JAILSON DURAES CORDEIRO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,73 4 30 3,00 2,80 3,00 -...","17,03",Aprovado
21,0338114048,JAILSON TEIXEIRA DE SOUSA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 2,00 1,87 2 30 2,00 3,40 1,00 -...","15,77",Aprovado
22,0338128769,JAIR FERREIRA NEVES NETO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 2,00 1,83 2 24 1,50 2,20 3,00 -...","15,53",Aprovado
23,0338126671,JEAN MOUTINHO BREVES DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,80 3 30 1,50 3,40 2,00 -...","15,20",Aprovado
24,0338121952,JOAO PAULO VAZ DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,04 11 23 1,20 0,60 1,00 ...","9,84",Eliminado. Item 11.2 .17.
25,0338119398,JONATAS DA SILVA TEIXEIRA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,36 9 28 1,00 1,00 1,00 -...","11,36",Aprovado
26,0338124791,JOSE DA CONCEICAO FERREIRA NETO,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
27,0338132676,JOSE MARIA MANGUEIRA NETO,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,50 6 24 1,10 0,00 0,00 -...","8,10",Eliminado. Item 11.2 .17.
28,0338102217,JOSE MATIAS DE SANTANA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,05 10 21 1,50 1,60 2,50 ...","12,65",Aprovado
29,0338128172,JULIO BREVES DOS SANTOS NETO,102,Analista de Tecnologia da Informação,"1,50 1,00 1,50 1,00 0,00 25 25 1,00 1,80 0,30 ...","8,10",Eliminado. Item 11.2 .17.
30,0338126926,KAMILA RODRIGUES GOMES,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 2,00 1,53 7 30 3,00 1,60 0,80 -...","14,93",Aprovado
31,0338125078,LAMARTINE CEZAR MONTEIRO GOMES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,50 1,80 3 30 2,00 1,00 2,00 -...","12,80",Aprovado
32,0338109903,LARYSSA FERREIRA DA SILVA,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
33,0338117749,LEONARDO MAFFEI DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 2,00 1,42 7 24 2,00 1,80 2,00 -...","14,22",Aprovado
34,0338127087,LOURIVAL SABINO DA SILVA JUNIOR,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,42 7 24 1,50 2,80 1,00 -...","12,22",Aprovado
35,0338112524,LUCAS GUEDES PIRES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,47 8 30 3,00 1,00 2,00 -...","13,47",Aprovado
36,0338108444,LUCAS RAPHAEL FERREIRA DE MIRANDA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,73 4 30 1,80 1,00 3,00 -...","14,53",Aprovado
37,0338112461,LUCIANA CHAVES SANTOS VASCONCELLOS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 1,59 6 29 1,50 2,20 1,80 -...","13,09",Aprovado
38,0338109968,LUIS EMANUEL NEVES DE JESUS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,33 10 30 1,80 2,20 3,00 ...","13,83",Aprovado
39,0338111022,LUIZ FELIPE CABRAL NEVES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,83 2 24 1,50 2,20 3,00 -...","14,53",Aprovado
40,0338127942,LUIZ FILIPE DE ALMEIDA RIBEIRO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,62 5 26 1,00 2,50 2,00 -...","13,62",Aprovado
41,0338126578,MANOEL ENISON RAMOS VIANA,102,Analista de Tecnologia da Informação,"1,00 1,50 1,50 1,50 1,14 12 28 3,00 2,80 3,00 ...","15,44",Aprovado
42,0338125612,MARCELLO GOMES MARQUES FILHO,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 0,93 16 30 1,50 3,40 2,00 ...","13,83",Aprovado
43,0338121405,MARCELO ALVES CARDOSO LOPES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,24 8 21 1,70 2,20 2,00 -...","13,14",Aprovado
44,0338120357,MARCELO OTAVIO CARDOSO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,38 9 29 1,20 1,60 2,50 -...","13,18",Aprovado
45,0338116632,MARCELO SPIGOLON PEREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 1,19 11 27 2,50 2,20 1,50 ...","13,39",Aprovado
46,0338108067,MARCILEIDE CARDOSO DE SOUZA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,19 11 27 0,50 0,00 3,00 ...","10,69",Aprovado
47,0338112144,MARCIO CHARLES DOS SANTOS OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,40 9 30 1,20 2,30 2,50 -...","13,90",Aprovado
48,0338106219,MARCOS ALVES DE OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,47 8 30 1,50 2,70 1,00 -...","13,67",Aprovado
49,0338113576,MARCOS VINICIUS GOMES DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 1,55 5 22 1,50 0,00 0,00 -...","8,05",Eliminado. Item 11.2 .17.
50,0338104350,MARCOS VINICIUS JANO DA SILVA,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,04 11 23 1,00 3,40 2,00 ...","12,94",Aprovado
51,0338113314,MARIA APARECIDA SOUSA FERREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 0,93 16 30 1,00 0,60 2,00 ...","10,53",Aprovado
52,0338104760,MARIANA APARECIDA PEREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 2,00 0 24 1,50 1,60 1,00 -...","11,60",Aprovado

In [ ]:
col_names = ['Num de inscrição', 'Nome Candidato', 'Vaga', 'Cargo', 'Notas', 'NPD', 'Situação']
df_resposta_tab_02 = pd.DataFrame(columns=col_names)

df_resposta_tab_02['Num de inscrição'] = df_tabela_02['Unnamed: 0']
df_resposta_tab_02['Nome Candidato'] = df_tabela_02['Unnamed: 1']
df_resposta_tab_02['Vaga'] = df_tabela_02['Unnamed: 2']
df_resposta_tab_02['Cargo'] = df_tabela_02['Unnamed: 3']
df_resposta_tab_02['Notas'] = df_tabela_02['Nota Preliminar Pontuação preliminar nos Parâmetros Resultado preliminar nos']
df_resposta_tab_02['NPD'] = df_tabela_02['Unnamed: 4']
df_resposta_tab_02['Situação'] = df_tabela_02['Unnamed: 5']

# Display the new DataFrame
df_resposta_tab_02

,Num de inscrição,Nome Candidato,Vaga,Cargo,Notas,NPD,Situação
4,0338123128,FERNANDO VINICIUS GONCALVES DE SOUZA,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
5,0338119704,FILIPE BARBOSA LIMA,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 2,00 0,67 20 30 1,50 2,80 3,00 ...","15,97",Aprovado
6,0338101937,FILIPE FERNANDES DE OLIVEIRA NASCIMENTO,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,23 10 26 1,50 2,50 2,00 ...","12,73",Aprovado
7,0338124136,FILIPE GUIMARAES DE OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 1,64 5 28 1,50 0,90 2,00 -...","11,04",Aprovado
8,0338105407,FRANCISCO ALISSON COSTA LOPES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,46 7 26 2,00 1,00 3,00 -...","13,96",Aprovado
9,0338103222,FRED ULISSES MARANHAO,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,77 3 26 1,50 4,00 1,00 -...","13,77",Aprovado
10,0338132606,GABRIEL HELENO GONCALVES DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,73 4 30 2,00 2,20 1,50 -...","13,93",Aprovado
11,0338121740,GABRIEL MENDONCA FERNANDES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 1,42 7 24 1,50 0,60 1,00 -...","10,52",Aprovado
12,0338106751,GABRIEL MOTA DA CAMARA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,57 6 28 2,50 1,60 2,50 -...","14,67",Aprovado
13,0338127224,GEDAIAS ELOI BRANDAO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,27 11 30 3,00 0,60 3,00 ...","13,87",Aprovado
14,0338113173,GIOVANNI CUNHA DE AMORIM,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,70 4 27 2,00 1,00 2,00 -...","12,70",Aprovado
15,0338118047,GUILHERME DE SOUZA PEREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,65 4 23 1,50 2,20 0,50 -...","11,85",Aprovado
16,0338131306,GUILHERME PASSOS CAMPOS,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
17,0338108957,GUSTAVO HENRIQUE ALVES RODRIGUES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,60 6 30 1,00 2,20 2,50 -...","13,30",Aprovado
18,0338121253,HENRIQUE PEREIRA DE FREITAS FILHO,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,53 7 30 1,80 4,00 2,00 -...","14,83",Aprovado
19,0338109956,IALA PATRICIA DE JESUS MONTEIRO DE JESUS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,67 5 30 3,00 0,60 2,00 -...","13,27",Aprovado
20,0338115090,JAILSON DURAES CORDEIRO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,73 4 30 3,00 2,80 3,00 -...","17,03",Aprovado
21,0338114048,JAILSON TEIXEIRA DE SOUSA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 2,00 1,87 2 30 2,00 3,40 1,00 -...","15,77",Aprovado
22,0338128769,JAIR FERREIRA NEVES NETO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 2,00 1,83 2 24 1,50 2,20 3,00 -...","15,53",Aprovado
23,0338126671,JEAN MOUTINHO BREVES DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,80 3 30 1,50 3,40 2,00 -...","15,20",Aprovado
24,0338121952,JOAO PAULO VAZ DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,04 11 23 1,20 0,60 1,00 ...","9,84",Eliminado. Item 11.2 .17.
25,0338119398,JONATAS DA SILVA TEIXEIRA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,36 9 28 1,00 1,00 1,00 -...","11,36",Aprovado
26,0338124791,JOSE DA CONCEICAO FERREIRA NETO,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
27,0338132676,JOSE MARIA MANGUEIRA NETO,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,50 6 24 1,10 0,00 0,00 -...","8,10",Eliminado. Item 11.2 .17.
28,0338102217,JOSE MATIAS DE SANTANA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,05 10 21 1,50 1,60 2,50 ...","12,65",Aprovado
29,0338128172,JULIO BREVES DOS SANTOS NETO,102,Analista de Tecnologia da Informação,"1,50 1,00 1,50 1,00 0,00 25 25 1,00 1,80 0,30 ...","8,10",Eliminado. Item 11.2 .17.
30,0338126926,KAMILA RODRIGUES GOMES,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 2,00 1,53 7 30 3,00 1,60 0,80 -...","14,93",Aprovado
31,0338125078,LAMARTINE CEZAR MONTEIRO GOMES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,50 1,80 3 30 2,00 1,00 2,00 -...","12,80",Aprovado
32,0338109903,LARYSSA FERREIRA DA SILVA,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 0 0,00 0,00 0,00 - ...","0,00",Eliminado. Item 11.2 .10.
33,0338117749,LEONARDO MAFFEI DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 2,00 1,42 7 24 2,00 1,80 2,00 -...","14,22",Aprovado
34,0338127087,LOURIVAL SABINO DA SILVA JUNIOR,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,42 7 24 1,50 2,80 1,00 -...","12,22",Aprovado
35,0338112524,LUCAS GUEDES PIRES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,47 8 30 3,00 1,00 2,00 -...","13,47",Aprovado
36,0338108444,LUCAS RAPHAEL FERREIRA DE MIRANDA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,73 4 30 1,80 1,00 3,00 -...","14,53",Aprovado
37,0338112461,LUCIANA CHAVES SANTOS VASCONCELLOS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 1,59 6 29 1,50 2,20 1,80 -...","13,09",Aprovado
38,0338109968,LUIS EMANUEL NEVES DE JESUS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,33 10 30 1,80 2,20 3,00 ...","13,83",Aprovado
39,0338111022,LUIZ FELIPE CABRAL NEVES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,83 2 24 1,50 2,20 3,00 -...","14,53",Aprovado
40,0338127942,LUIZ FILIPE DE ALMEIDA RIBEIRO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,62 5 26 1,00 2,50 2,00 -...","13,62",Aprovado
41,0338126578,MANOEL ENISON RAMOS VIANA,102,Analista de Tecnologia da Informação,"1,00 1,50 1,50 1,50 1,14 12 28 3,00 2,80 3,00 ...","15,44",Aprovado
42,0338125612,MARCELLO GOMES MARQUES FILHO,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 0,93 16 30 1,50 3,40 2,00 ...","13,83",Aprovado
43,0338121405,MARCELO ALVES CARDOSO LOPES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,24 8 21 1,70 2,20 2,00 -...","13,14",Aprovado
44,0338120357,MARCELO OTAVIO CARDOSO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,38 9 29 1,20 1,60 2,50 -...","13,18",Aprovado
45,0338116632,MARCELO SPIGOLON PEREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 1,19 11 27 2,50 2,20 1,50 ...","13,39",Aprovado
46,0338108067,MARCILEIDE CARDOSO DE SOUZA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,19 11 27 0,50 0,00 3,00 ...","10,69",Aprovado
47,0338112144,MARCIO CHARLES DOS SANTOS OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,40 9 30 1,20 2,30 2,50 -...","13,90",Aprovado
48,0338106219,MARCOS ALVES DE OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 1,47 8 30 1,50 2,70 1,00 -...","13,67",Aprovado
49,0338113576,MARCOS VINICIUS GOMES DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 1,55 5 22 1,50 0,00 0,00 -...","8,05",Eliminado. Item 11.2 .17.
50,0338104350,MARCOS VINICIUS JANO DA SILVA,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,04 11 23 1,00 3,40 2,00 ...","12,94",Aprovado
51,0338113314,MARIA APARECIDA SOUSA FERREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 0,93 16 30 1,00 0,60 2,00 ...","10,53",Aprovado
52,0338104760,MARIANA APARECIDA PEREIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 2,00 0 24 1,50 1,60 1,00 -...","11,60",Aprovado

## Tratamento da Terceira Tabela

In [ ]:
tabela_inteira_3 = tabula.read_pdf("resultadoObjetiva.pdf", pages="6")

df_tabela_03 = pd.DataFrame(tabela_inteira_3[0])
df_tabela_03 = df_tabela_03[4:] # Remove as 4 primeiras linhas de cada tabela
df_tabela_03 = df_tabela_03.dropna(axis=1, how='all')
df_tabela_03

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Nota Preliminar Pontuação preliminar nos Parâmetros Resultado preliminar nos,Unnamed: 4,Unnamed: 5
4,0338120599,MATEUS MANUEL RODRIGUES BEZERRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,60 6 30 1,50 2,80 2,00 -...","14,40",Aprovado
5,0338122580,MATHEUS SANTOS ALENCAR,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 0,93 15 28 1,50 2,20 1,50 ...","12,13",Aprovado
6,0338127929,PEDRO ARAUJO CHAVES JUNIOR,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 1,00 1,80 3 30 3,00 3,40 3,00 -...","18,20",Aprovado
7,0338119964,RAFAEL ARAUJO GOMES DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 2,00 0 25 1,20 1,70 1,50 -...","12,40",Aprovado
8,0338111404,RAFAEL AUGUSTO DE OLIVEIRA MARTINS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,00 1,00 0,44 21 27 1,00 1,50 1,00 ...","8,94",Eliminado. Item 11.2 .17.
9,0338103155,RAFAEL BRENNER GOMES SILVA,102,Analista de Tecnologia da Informação,"1,00 1,50 1,00 1,00 0,86 12 21 0,50 0,00 1,50 ...","7,36",Eliminado. Item 11.2 .17.
10,0338132733,RAFAEL RAMON ALVES TEIXEIRA DE OLIVEIRA,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,45 8 29 2,00 1,60 2,00 -...","12,55",Aprovado
11,0338113882,RAMON MONTALVAO ALVES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,70 3 20 1,00 1,70 0,50 -...","10,40",Aprovado
12,0338104384,ROBERTO MIRANDA TORGA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 1,38 8 26 2,00 2,20 2,00 -...","13,58",Aprovado
13,0338100110,RODOLFO ANTONIO SILVA,102,Analista de Tecnologia da Informação,"1,50 2,00 1,50 1,50 1,87 2 30 1,50 1,90 2,50 -...","14,27",Aprovado
14,0338114348,ROSANA CRISTINA DA COSTA BARBOSA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,76 3 25 2,00 1,50 1,50 -...","12,26",Aprovado
15,0338107715,SAMUEL LUCAS IRENE DIONISIO DE MORAES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,50 1,73 4 30 1,00 1,70 1,50 -...","11,93",Aprovado
16,0338125161,SAMUEL OLIVEIRA DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,04 11 23 1,50 1,10 2,00 ...","11,14",Aprovado
17,0338117658,SAULO ROMAO JUNIOR,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,30 8 23 1,00 4,00 2,00 -...","13,80",Aprovado
18,0338116952,SERGIO MATOS DE ANDRADE,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,73 3 22 2,00 1,70 2,00 -...","12,93",Aprovado
19,0338130645,TALES MARINHO GODOIS,102,Analista de Tecnologia da Informação,"1,50 2,00 1,50 1,00 1,33 10 30 1,00 3,10 1,50 ...","12,93",Aprovado
20,0338112078,TATIANE PEREIRA QUEIROZ,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 0,96 13 25 1,00 0,00 3,00 ...","9,96",Eliminado. Item 11.2 .17.
21,0338113810,THALES ARAUJO CRONEMBERGER,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 2,00 0 30 1,20 3,40 2,50 -...","16,10",Aprovado
22,0338101820,THEOGENES FERREIRA DUARTE,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 1,66 5 29 1,00 1,00 2,00 -...","11,66",Aprovado
23,0338103726,TIAGO OLIVEIRA LOUP,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,00 1,33 10 30 1,50 1,00 0,50 ...","10,83",Aprovado
24,0338106098,VICTOR GONCALVES DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,80 3 30 1,50 1,60 2,00 -...","13,40",Aprovado
25,0338126123,VICTORIA DA SILVA GOMES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,50 0,64 15 22 1,50 0,00 1,00 ...","8,64",Eliminado. Item 11.2 .17.
26,0338117326,VINICIUS DA SILVA CARVALHO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,53 7 30 1,80 1,60 2,00 -...","12,93",Aprovado
27,0338106010,WAGNER DA COSTA ALVES DE JESUS,102,Analista de Tecnologia da Informação,"1,50 1,00 1,50 1,00 1,76 3 25 1,00 1,00 0,00 -...","8,76",Eliminado. Item 11.2 .17.
28,0338126992,WANDERSON FERREIRA DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,53 7 30 1,00 1,10 2,00 -...","11,13",Aprovado
29,0338133336,WANESSA GUIMARAES CARDOSO,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 23 0,00 0,00 0,00 -...","0,00",Eliminado. Item 11.2 .10.
30,0338127073,WELDEN SOUZA DE AGUIAR,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,20 10 25 1,00 2,20 2,00 ...","11,90",Aprovado
31,0338115836,WILLIAMS VIEIRA FIGUEIROA,102,Analista de Tecnologia da Informação,"1,00 1,00 1,00 1,00 0,82 13 22 1,50 1,60 1,00 ...","8,92",Eliminado. Item 11.2 .17.
32,0338112239,WILLIAN ROBERTO FRANCO,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 1,70 4 27 1,50 1,60 2,00 -...","12,80",Aprovado
33,0338113732,WILTON CANDIDO DOS SANTOS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,00 1,00 1,92 1 24 1,00 0,50 1,00 -...","9,42",Eliminado. Item 11.2 .17.
34,0338114403,WISLAN PABLO SANTOS DE SOUZA,102,Analista de Tecnologia da Informação,"1,50 2,00 1,50 2,00 1,53 7 30 2,00 1,00 2,00 -...","13,53",Aprovado
35,0338125509,ADRIANA GAERTNER MARABUTO DOMINGUES,103,Bibliotecário,"2,00 1,50 1,00 1,50 1,20 12 30 1,00 2,00 1,50 ...","12,70",Aprovado
36,0338110236,ALAN JAMES CAMPOS RODRIGUES,103,Bibliotecário,"2,00 1,50 2,00 1,50 1,48 7 27 2,00 2,00 1,50 1...","15,48",Aprovado
37,0338106016,ALBERTH SANT ANA COSTA DA SILVA,103,Bibliotecário,"2,00 1,50 1,50 2,00 1,53 7 30 2,00 2,00 1,50 1...","15,53",Aprovado
38,0338117138,ALEXANDRE FERREIRA BOTTINO,103,Bibliotecário,"2,00 1,50 1,00 1,50 0,60 21 30 0,50 2,00 0,50 ...","10,60",Aprovado
39,0338113982,ALINE FERRARI DE MIRANDA FREITAS,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,66 5 29 0,50 1,00 1,50 1...","12,66",Aprovado
40,0338102898,ANA BEATRIZ MARQUES SILVA,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,72 4 29 0,50 0,50 1,00 1...","11,22",Aprovado
41,0338117059,ANDRIELLE GOMES MACEDO,103,Bibliotecário,"2,00 1,50 2,00 1,50 1,60 6 30 0,50 1,00 1,00 1...","12,10",Aprovado
42,0338103965,ANGELA PACELLI,103,Bibliotecário,"2,00 2,00 2,00 1,50 1,87 2 30 1,50 1,00 1,50 2...","15,37",Aprovado
43,0338130501,ANNA CAROLINA ANTUNES DE MORAES,103,Bibliotecário,"2,00 2,00 2,00 2,00 1,73 4 30 1,50 2,00 1,50 2...","16,73",Aprovado
44,0338118020,CAMILA DE OLIVEIRA CANDIDO,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,67 5 30 1,50 0,50 1,50 1...","13,17",Aprovado
45,0338108254,CAMILLA FARIA NALIN,103,Bibliotecário,"2,00 1,50 1,50 2,00 1,03 14 29 0,50 2,00 0,50 ...","12,03",Aprovado
46,0338102435,CAROLINA COSTA NASCIMENTO,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,07 13 28 0,50 2,00 1,00 ...","13,07",Aprovado
47,0338128278,CRISTIANE CARDOSO ALMEIDA,103,Bibliotecário,"2,00 1,00 1,00 1,50 1,47 8 30 0,50 0,00 0,00 0...","7,97",Eliminado. Item 11.2 .17.
48,0338120363,DANILO DE ALBUQUERQUE FURTADO,103,Bibliotecário,"2,00 1,00 1,50 1,50 1,27 11 30 0,00 1,00 1,00 ...","10,77",Aprovado
49,0338128775,DENISE APARECIDA FREITAS DE ANDRADE,103,Bibliotecário,"2,00 2,00 1,00 1,50 1,13 13 30 0,00 1,00 1,00 ...","10,63",Aprovado
50,0338107344,DIENNER MORY RODRIGUES SILVA,103,Bibliotecário,"2,00 1,00 1,50 1,50 1,31 9 26 0,50 1,00 1,00 0...","10,31",Aprovado
51,0338104684,FERNANDA WESCHENFELDER,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,87 2 30 0,50 1,00 2,00 1...","12,87",Aprovado
52,0338124930,GABRIELA PINHEIRO DE MELO GOMES,103,Bibliotecário,"2,00 1,50 1,50 2,00 1,53 7 30 1,50 0,50 0,50 1...","12,03",Aprovado

In [ ]:
col_names_3 = ['Num de inscrição', 'Nome Candidato', 'Vaga', 'Cargo', 'Notas', 'NPD', 'Situação']
df_resposta_tab_03 = pd.DataFrame(columns=col_names_3)

df_resposta_tab_03['Num de inscrição'] = df_tabela_03['Unnamed: 0']
df_resposta_tab_03['Nome Candidato'] = df_tabela_03['Unnamed: 1']
df_resposta_tab_03['Vaga'] = df_tabela_03['Unnamed: 2']
df_resposta_tab_03['Cargo'] = df_tabela_03['Unnamed: 3']
df_resposta_tab_03['Notas'] = df_tabela_03['Nota Preliminar Pontuação preliminar nos Parâmetros Resultado preliminar nos']
df_resposta_tab_03['NPD'] = df_tabela_03['Unnamed: 4']
df_resposta_tab_03['Situação'] = df_tabela_03['Unnamed: 5']

# Display the new DataFrame
df_resposta_tab_03

,Num de inscrição,Nome Candidato,Vaga,Cargo,Notas,NPD,Situação
4,0338120599,MATEUS MANUEL RODRIGUES BEZERRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,60 6 30 1,50 2,80 2,00 -...","14,40",Aprovado
5,0338122580,MATHEUS SANTOS ALENCAR,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 0,93 15 28 1,50 2,20 1,50 ...","12,13",Aprovado
6,0338127929,PEDRO ARAUJO CHAVES JUNIOR,102,Analista de Tecnologia da Informação,"2,00 2,00 2,00 1,00 1,80 3 30 3,00 3,40 3,00 -...","18,20",Aprovado
7,0338119964,RAFAEL ARAUJO GOMES DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 2,00 0 25 1,20 1,70 1,50 -...","12,40",Aprovado
8,0338111404,RAFAEL AUGUSTO DE OLIVEIRA MARTINS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,00 1,00 0,44 21 27 1,00 1,50 1,00 ...","8,94",Eliminado. Item 11.2 .17.
9,0338103155,RAFAEL BRENNER GOMES SILVA,102,Analista de Tecnologia da Informação,"1,00 1,50 1,00 1,00 0,86 12 21 0,50 0,00 1,50 ...","7,36",Eliminado. Item 11.2 .17.
10,0338132733,RAFAEL RAMON ALVES TEIXEIRA DE OLIVEIRA,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,45 8 29 2,00 1,60 2,00 -...","12,55",Aprovado
11,0338113882,RAMON MONTALVAO ALVES,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,70 3 20 1,00 1,70 0,50 -...","10,40",Aprovado
12,0338104384,ROBERTO MIRANDA TORGA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,50 1,38 8 26 2,00 2,20 2,00 -...","13,58",Aprovado
13,0338100110,RODOLFO ANTONIO SILVA,102,Analista de Tecnologia da Informação,"1,50 2,00 1,50 1,50 1,87 2 30 1,50 1,90 2,50 -...","14,27",Aprovado
14,0338114348,ROSANA CRISTINA DA COSTA BARBOSA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,76 3 25 2,00 1,50 1,50 -...","12,26",Aprovado
15,0338107715,SAMUEL LUCAS IRENE DIONISIO DE MORAES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,50 1,73 4 30 1,00 1,70 1,50 -...","11,93",Aprovado
16,0338125161,SAMUEL OLIVEIRA DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,00 1,00 1,04 11 23 1,50 1,10 2,00 ...","11,14",Aprovado
17,0338117658,SAULO ROMAO JUNIOR,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,30 8 23 1,00 4,00 2,00 -...","13,80",Aprovado
18,0338116952,SERGIO MATOS DE ANDRADE,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,73 3 22 2,00 1,70 2,00 -...","12,93",Aprovado
19,0338130645,TALES MARINHO GODOIS,102,Analista de Tecnologia da Informação,"1,50 2,00 1,50 1,00 1,33 10 30 1,00 3,10 1,50 ...","12,93",Aprovado
20,0338112078,TATIANE PEREIRA QUEIROZ,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,00 0,96 13 25 1,00 0,00 3,00 ...","9,96",Eliminado. Item 11.2 .17.
21,0338113810,THALES ARAUJO CRONEMBERGER,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,50 2,00 0 30 1,20 3,40 2,50 -...","16,10",Aprovado
22,0338101820,THEOGENES FERREIRA DUARTE,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 1,66 5 29 1,00 1,00 2,00 -...","11,66",Aprovado
23,0338103726,TIAGO OLIVEIRA LOUP,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,00 1,33 10 30 1,50 1,00 0,50 ...","10,83",Aprovado
24,0338106098,VICTOR GONCALVES DOS SANTOS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,50 1,80 3 30 1,50 1,60 2,00 -...","13,40",Aprovado
25,0338126123,VICTORIA DA SILVA GOMES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,00 1,50 0,64 15 22 1,50 0,00 1,00 ...","8,64",Eliminado. Item 11.2 .17.
26,0338117326,VINICIUS DA SILVA CARVALHO,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,53 7 30 1,80 1,60 2,00 -...","12,93",Aprovado
27,0338106010,WAGNER DA COSTA ALVES DE JESUS,102,Analista de Tecnologia da Informação,"1,50 1,00 1,50 1,00 1,76 3 25 1,00 1,00 0,00 -...","8,76",Eliminado. Item 11.2 .17.
28,0338126992,WANDERSON FERREIRA DA SILVA,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,53 7 30 1,00 1,10 2,00 -...","11,13",Aprovado
29,0338133336,WANESSA GUIMARAES CARDOSO,102,Analista de Tecnologia da Informação,"0,00 0,00 0,00 0,00 0,00 0 23 0,00 0,00 0,00 -...","0,00",Eliminado. Item 11.2 .10.
30,0338127073,WELDEN SOUZA DE AGUIAR,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,20 10 25 1,00 2,20 2,00 ...","11,90",Aprovado
31,0338115836,WILLIAMS VIEIRA FIGUEIROA,102,Analista de Tecnologia da Informação,"1,00 1,00 1,00 1,00 0,82 13 22 1,50 1,60 1,00 ...","8,92",Eliminado. Item 11.2 .17.
32,0338112239,WILLIAN ROBERTO FRANCO,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 1,70 4 27 1,50 1,60 2,00 -...","12,80",Aprovado
33,0338113732,WILTON CANDIDO DOS SANTOS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,00 1,00 1,92 1 24 1,00 0,50 1,00 -...","9,42",Eliminado. Item 11.2 .17.
34,0338114403,WISLAN PABLO SANTOS DE SOUZA,102,Analista de Tecnologia da Informação,"1,50 2,00 1,50 2,00 1,53 7 30 2,00 1,00 2,00 -...","13,53",Aprovado
35,0338125509,ADRIANA GAERTNER MARABUTO DOMINGUES,103,Bibliotecário,"2,00 1,50 1,00 1,50 1,20 12 30 1,00 2,00 1,50 ...","12,70",Aprovado
36,0338110236,ALAN JAMES CAMPOS RODRIGUES,103,Bibliotecário,"2,00 1,50 2,00 1,50 1,48 7 27 2,00 2,00 1,50 1...","15,48",Aprovado
37,0338106016,ALBERTH SANT ANA COSTA DA SILVA,103,Bibliotecário,"2,00 1,50 1,50 2,00 1,53 7 30 2,00 2,00 1,50 1...","15,53",Aprovado
38,0338117138,ALEXANDRE FERREIRA BOTTINO,103,Bibliotecário,"2,00 1,50 1,00 1,50 0,60 21 30 0,50 2,00 0,50 ...","10,60",Aprovado
39,0338113982,ALINE FERRARI DE MIRANDA FREITAS,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,66 5 29 0,50 1,00 1,50 1...","12,66",Aprovado
40,0338102898,ANA BEATRIZ MARQUES SILVA,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,72 4 29 0,50 0,50 1,00 1...","11,22",Aprovado
41,0338117059,ANDRIELLE GOMES MACEDO,103,Bibliotecário,"2,00 1,50 2,00 1,50 1,60 6 30 0,50 1,00 1,00 1...","12,10",Aprovado
42,0338103965,ANGELA PACELLI,103,Bibliotecário,"2,00 2,00 2,00 1,50 1,87 2 30 1,50 1,00 1,50 2...","15,37",Aprovado
43,0338130501,ANNA CAROLINA ANTUNES DE MORAES,103,Bibliotecário,"2,00 2,00 2,00 2,00 1,73 4 30 1,50 2,00 1,50 2...","16,73",Aprovado
44,0338118020,CAMILA DE OLIVEIRA CANDIDO,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,67 5 30 1,50 0,50 1,50 1...","13,17",Aprovado
45,0338108254,CAMILLA FARIA NALIN,103,Bibliotecário,"2,00 1,50 1,50 2,00 1,03 14 29 0,50 2,00 0,50 ...","12,03",Aprovado
46,0338102435,CAROLINA COSTA NASCIMENTO,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,07 13 28 0,50 2,00 1,00 ...","13,07",Aprovado
47,0338128278,CRISTIANE CARDOSO ALMEIDA,103,Bibliotecário,"2,00 1,00 1,00 1,50 1,47 8 30 0,50 0,00 0,00 0...","7,97",Eliminado. Item 11.2 .17.
48,0338120363,DANILO DE ALBUQUERQUE FURTADO,103,Bibliotecário,"2,00 1,00 1,50 1,50 1,27 11 30 0,00 1,00 1,00 ...","10,77",Aprovado
49,0338128775,DENISE APARECIDA FREITAS DE ANDRADE,103,Bibliotecário,"2,00 2,00 1,00 1,50 1,13 13 30 0,00 1,00 1,00 ...","10,63",Aprovado
50,0338107344,DIENNER MORY RODRIGUES SILVA,103,Bibliotecário,"2,00 1,00 1,50 1,50 1,31 9 26 0,50 1,00 1,00 0...","10,31",Aprovado
51,0338104684,FERNANDA WESCHENFELDER,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,87 2 30 0,50 1,00 2,00 1...","12,87",Aprovado
52,0338124930,GABRIELA PINHEIRO DE MELO GOMES,103,Bibliotecário,"2,00 1,50 1,50 2,00 1,53 7 30 1,50 0,50 0,50 1...","12,03",Aprovado

##União de tabelas e preparando database de Cargo Analista de TI

In [ ]:
df_resposta = pd.concat([df_resposta_tab_01, df_resposta_tab_02, df_resposta_tab_03])
df_resposta

,Num de inscrição,Nome Candidato,Vaga,Cargo,Notas,NPD,Situação
4,0338110030,VENANCIO HENRIQUE DA SILVA,101,Advogado,"1,00 1,50 1,00 0,50 1,36 8 25 2,50 1,00 1,00 2...","11,86",Aprovado
5,0338133616,VICTOR MINERVINO QUINTIERE,101,Advogado,"0,50 1,50 1,00 1,00 0,80 18 30 2,50 0,50 0,50 ...","9,80",Eliminado. Item 11.2 .17.
6,0338113763,VINICIUS CUNHA E SILVA,101,Advogado,"1,50 1,50 1,50 1,50 1,00 15 30 3,00 0,50 0,50 ...","13,00",Aprovado
7,0338111127,VINICIUS LOPES ALVES VIEIRA,101,Advogado,"1,00 1,50 1,00 2,00 0,55 21 29 2,50 0,50 0,50 ...","12,05",Aprovado
8,0338109487,VINNY SOUSA DE QUEIROZ,101,Advogado,"1,50 1,50 1,50 1,00 1,20 12 30 3,00 1,00 0,50 ...","13,70",Aprovado
...,...,...,...,...,...,...,...
48,0338120363,DANILO DE ALBUQUERQUE FURTADO,103,Bibliotecário,"2,00 1,00 1,50 1,50 1,27 11 30 0,00 1,00 1,00 ...","10,77",Aprovado
49,0338128775,DENISE APARECIDA FREITAS DE ANDRADE,103,Bibliotecário,"2,00 2,00 1,00 1,50 1,13 13 30 0,00 1,00 1,00 ...","10,63",Aprovado
50,0338107344,DIENNER MORY RODRIGUES SILVA,103,Bibliotecário,"2,00 1,00 1,50 1,50 1,31 9 26 0,50 1,00 1,00 0...","10,31",Aprovado
51,0338104684,FERNANDA WESCHENFELDER,103,Bibliotecário,"2,00 1,50 1,50 1,50 1,87 2 30 0,50 1,00 2,00 1...","12,87",Aprovado
52,0338124930,GABRIELA PINHEIRO DE MELO GOMES,103,Bibliotecário,"2,00 1,50 1,50 2,00 1,53 7 30 1,50 0,50 0,50 1...","12,03",Aprovado

In [ ]:
# Exibe as linhas onde a coluna 'Cargo' contém 'Analista de Tecnologia da Informação'
analistas_ti = df_resposta[df_resposta['Cargo'].str.contains('Analista de Tecnologia da Informação', na=False)]
analistas_ti

,Num de inscrição,Nome Candidato,Vaga,Cargo,Notas,NPD,Situação
10,0338122137,ADALBERTO ROLIM NOGUEIRA,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,47 8 30 2,50 3,40 2,50 -...","15,87",Aprovado
11,0338126901,ALANE SERPA AMARAL,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,50 7 28 1,80 1,90 2,00 -...","12,70",Aprovado
12,0338102604,ALDERIAN GOMES DE GOIS,102,Analista de Tecnologia da Informação,"2,00 1,50 1,50 1,00 1,17 12 29 1,00 2,80 1,50 ...","12,47",Aprovado
13,0338114429,ALEX DE OLIVEIRA MEIRELES,102,Analista de Tecnologia da Informação,"2,00 1,00 1,50 1,00 1,54 6 26 2,00 1,50 2,00 -...","12,54",Aprovado
14,0338132128,ALEX FRANCO OLIVEIRA,102,Analista de Tecnologia da Informação,"2,00 2,00 1,50 1,00 1,00 15 30 3,00 1,90 2,70 ...","15,10",Aprovado
...,...,...,...,...,...,...,...
30,0338127073,WELDEN SOUZA DE AGUIAR,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,00 1,20 10 25 1,00 2,20 2,00 ...","11,90",Aprovado
31,0338115836,WILLIAMS VIEIRA FIGUEIROA,102,Analista de Tecnologia da Informação,"1,00 1,00 1,00 1,00 0,82 13 22 1,50 1,60 1,00 ...","8,92",Eliminado. Item 11.2 .17.
32,0338112239,WILLIAN ROBERTO FRANCO,102,Analista de Tecnologia da Informação,"1,50 1,50 1,50 1,50 1,70 4 27 1,50 1,60 2,00 -...","12,80",Aprovado
33,0338113732,WILTON CANDIDO DOS SANTOS,102,Analista de Tecnologia da Informação,"1,50 1,50 1,00 1,00 1,92 1 24 1,00 0,50 1,00 -...","9,42",Eliminado. Item 11.2 .17.
34,0338114403,WISLAN PABLO SANTOS DE SOUZA,102,Analista de Tecnologia da Informação,"1,50 2,00 1,50 2,00 1,53 7 30 2,00 1,00 2,00 -...","13,53",Aprovado

###Transformação: coletando apenas os dados necessários para análise

In [ ]:
analistas_ti_final = analistas_ti.drop('Vaga', axis=1)
analistas_ti_final = analistas_ti_final.drop('Notas', axis=1)
analistas_ti_final

,Num de inscrição,Nome Candidato,Cargo,NPD,Situação
10,0338122137,ADALBERTO ROLIM NOGUEIRA,Analista de Tecnologia da Informação,"15,87",Aprovado
11,0338126901,ALANE SERPA AMARAL,Analista de Tecnologia da Informação,"12,70",Aprovado
12,0338102604,ALDERIAN GOMES DE GOIS,Analista de Tecnologia da Informação,"12,47",Aprovado
13,0338114429,ALEX DE OLIVEIRA MEIRELES,Analista de Tecnologia da Informação,"12,54",Aprovado
14,0338132128,ALEX FRANCO OLIVEIRA,Analista de Tecnologia da Informação,"15,10",Aprovado
...,...,...,...,...,...
30,0338127073,WELDEN SOUZA DE AGUIAR,Analista de Tecnologia da Informação,"11,90",Aprovado
31,0338115836,WILLIAMS VIEIRA FIGUEIROA,Analista de Tecnologia da Informação,"8,92",Eliminado. Item 11.2 .17.
32,0338112239,WILLIAN ROBERTO FRANCO,Analista de Tecnologia da Informação,"12,80",Aprovado
33,0338113732,WILTON CANDIDO DOS SANTOS,Analista de Tecnologia da Informação,"9,42",Eliminado. Item 11.2 .17.
34,0338114403,WISLAN PABLO SANTOS DE SOUZA,Analista de Tecnologia da Informação,"13,53",Aprovado

In [ ]:
# Filtra o DataFrame para incluir apenas registros com 'Situacao' igual a 'Aprovado'
aprovados_ti_disc = analistas_ti_final[analistas_ti_final['Situação'] == 'Aprovado']
aprovados_ti_disc

,Num de inscrição,Nome Candidato,Cargo,NPD,Situação
10,0338122137,ADALBERTO ROLIM NOGUEIRA,Analista de Tecnologia da Informação,"15,87",Aprovado
11,0338126901,ALANE SERPA AMARAL,Analista de Tecnologia da Informação,"12,70",Aprovado
12,0338102604,ALDERIAN GOMES DE GOIS,Analista de Tecnologia da Informação,"12,47",Aprovado
13,0338114429,ALEX DE OLIVEIRA MEIRELES,Analista de Tecnologia da Informação,"12,54",Aprovado
14,0338132128,ALEX FRANCO OLIVEIRA,Analista de Tecnologia da Informação,"15,10",Aprovado
...,...,...,...,...,...
26,0338117326,VINICIUS DA SILVA CARVALHO,Analista de Tecnologia da Informação,"12,93",Aprovado
28,0338126992,WANDERSON FERREIRA DA SILVA,Analista de Tecnologia da Informação,"11,13",Aprovado
30,0338127073,WELDEN SOUZA DE AGUIAR,Analista de Tecnologia da Informação,"11,90",Aprovado
32,0338112239,WILLIAN ROBERTO FRANCO,Analista de Tecnologia da Informação,"12,80",Aprovado
34,0338114403,WISLAN PABLO SANTOS DE SOUZA,Analista de Tecnologia da Informação,"13,53",Aprovado

#Tratamento de Dados com as Notas Objetivas

In [ ]:
# Initialize an empty list to store DataFrames
df_list = []

# Iterate through pages 45 to 53
for page in range(45, 54):
    try:
        # Read tables from each page
        tables = tabula.read_pdf("resultadoObjetiva_1.pdf", pages=str(page))

        # Iterate through each table on the page
        for table in tables:
            # Convert the table to a DataFrame
            df = pd.DataFrame(table)
            # Append to the list
            df_list.append(df)
    except Exception as e:
        print(f"Error processing page {page}: {e}")

# Concatenate all DataFrames in the list
if df_list:
    df_tabela_obj = pd.concat(df_list, ignore_index=True)
    print(df_tabela_obj.head()) # Print the first few rows
else:
    print("No tables found in the specified pages.")

   Código\rdo Cargo                              Ocupação     Incrição  \
0               NaN                                   NaN          NaN
1             101.0                              ADVOGADO  338111225.0
2             101.0                              ADVOGADO  338103543.0
3             101.0                              ADVOGADO  338128144.0
4             102.0  ANALISTA DE TECNOLOGIA DA INFORMACAO  338115090.0

                     Nome do Candidato Solicitou\rconcorrer  \
0                                  PCD                  PNP
1               CAREM RIBEIRO DE SOUZA                  Não
2            THIAGO DE JESUS FONTENELE                  Não
3  MARIA LUIZA DIAS CUSTODIO GUIMARAES                  Não
4              JAILSON DURAES CORDEIRO                  Não

                     Data de\rNascimento   Tipo de\rProva  \
0  Língua\rPortuguesa e\rRedação Oficial  Legislação\rCFM
1                                    Não       31/03/1979
2                                    Não       06/08/1984
3                                    Não       20/01/1984
4                                    Sim       24/07/1989

  Pontuação final nas Áreas de Conhecimento              Nota Final  \
0                      Legislação\rEspecial  Conhecimentos\rBásicos
1                                         A                       5
2                                         C                       6
3                                         D                       7
4                                         B                       7

                     Situação  ...  \
0  Conhecimentos\rEspecíficos  ...
1                           4  ...
2                           3  ...
3                           5  ...
4                           3  ...

  Convocado para correção\rda prova\rdiscrusiva/redação Unnamed: 0 Unnamed: 1  \
0                                                Pcd           Pnp        A.C
1                                                 13            12         25
2                                                 13            12         25
3                                                 14            11         25
4                                                 14            24         38

  Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8
0        Pcd        Pnp        NaN        NaN        NaN        NaN        NaN
1   Aprovado       1321          -          -          -          -          -
2   Aprovado       1322          -          -          -          -          -
3   Aprovado       1323          -          -          -          -          -
4   Aprovado          1          -          1        Sim          -        Sim

[5 rows x 21 columns]

In [ ]:
df_tabela_obj.shape

(279, 21)

In [ ]:
df_tabela_obj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 21 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
do Cargo                                      270 non-null    float64
 1   Ocupação                                             270 non-null    object
 2   Incrição                                             270 non-null    float64
 3   Nome do Candidato                                    279 non-null    object
concorrer                                  279 non-null    object
Nascimento                                   279 non-null    object
Prova                                        279 non-null    object
 7   Pontuação final nas Áreas de Conhecimento            279 non-null    object
 8   Nota Final                                           279 non-null    object
 9   Situação                                             279 non-null    object
 10  Classificação                                        279 non-null    object
discrusiva/redação  279 non-null    object
 12  Unnamed: 0                                           279 non-null    object
 13  Unnamed: 1                                           279 non-null    object
 14  Unnamed: 2                                           279 non-null    object
 15  Unnamed: 3                                           279 non-null    object
 16  Unnamed: 4                                           270 non-null    object
 17  Unnamed: 5                                           270 non-null    object
 18  Unnamed: 6                                           270 non-null    object
 19  Unnamed: 7                                           270 non-null    object
 20  Unnamed: 8                                           270 non-null    object
dtypes: float64(2), object(19)
memory usage: 45.9+ KB

In [ ]:
#col_names = ['Num de inscrição', 'Nome Candidato', 'Vaga', 'Cargo', 'Notas', 'NPD', 'Situação']
col_names = ['Código\rdo Cargo', 'Ocupação', 'Incrição', 'Nome do Candidato','Solicitou\rconcorrer', 'Data de\rNascimento', 'Tipo de\rProva',
       'Pontuação final nas Áreas de Conhecimento', 'Nota Final', 'Situação', 'Classificação',
       'Convocado para correção\rda prova\rdiscrusiva/redação', 'Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']
df_resposta_obj = pd.DataFrame(columns=col_names)
df_resposta_obj = df_tabela_obj.drop(['Solicitou\rconcorrer', 'Data de\rNascimento'], axis=1)
df_resposta_obj = df_resposta_obj.drop(['Nota Final', 'Situação', 'Classificação', 'Convocado para correção\rda prova\rdiscrusiva/redação', 'Unnamed: 0', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8'], axis=1)


df_resposta_obj['Tipo_Prova'] = df_resposta_obj['Pontuação final nas Áreas de Conhecimento']
df_resposta_obj['Nota_obj'] = df_resposta_obj['Unnamed: 1']
df_resposta_obj['Situação_obj'] = df_resposta_obj['Unnamed: 2']
df_resposta_obj['Ranking_obj'] = df_resposta_obj['Unnamed: 3']

df_resposta_obj = df_resposta_obj.drop(['Pontuação final nas Áreas de Conhecimento', 'Tipo de\rProva', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3'], axis=1)
df_resposta_obj = df_resposta_obj[1:] # Remove a primeira linha de cada tabela
df_resposta_obj['Incrição'] = df_resposta_obj['Incrição'].astype(str)
df_resposta_obj['Incrição'] = df_resposta_obj['Incrição'].str.replace('.0', '').astype(object)
df_resposta_obj['Incrição'] = df_resposta_obj['Incrição'].str.zfill(10)

# Display the new DataFrame
df_resposta_obj

,Código\rdo Cargo,Ocupação,Incrição,Nome do Candidato,Tipo_Prova,Nota_obj,Situação_obj,Ranking_obj
1,101.0,ADVOGADO,0338111225,CAREM RIBEIRO DE SOUZA,A,25,Aprovado,1321
2,101.0,ADVOGADO,0338103543,THIAGO DE JESUS FONTENELE,C,25,Aprovado,1322
3,101.0,ADVOGADO,0338128144,MARIA LUIZA DIAS CUSTODIO GUIMARAES,D,25,Aprovado,1323
4,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338115090,JAILSON DURAES CORDEIRO,B,38,Aprovado,1
5,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338104384,ROBERTO MIRANDA TORGA,B,37,Aprovado,2
...,...,...,...,...,...,...,...,...
274,103.0,BIBLIOTECARIO,0338126207,ROSA MARIA DE JESUS,U,31,Aprovado,17
275,103.0,BIBLIOTECARIO,0338120363,DANILO DE ALBUQUERQUE FURTADO,U,31,Aprovado,18
276,103.0,BIBLIOTECARIO,0338125509,ADRIANA GAERTNER MARABUTO DOMINGUES,U,30,Aprovado,19
277,103.0,BIBLIOTECARIO,0338102435,CAROLINA COSTA NASCIMENTO,U,30,Aprovado,20
278,103.0,BIBLIOTECARIO,0338118020,CAMILA DE OLIVEIRA CANDIDO,U,30,Aprovado,21

###Coletando apenas candidatos de Analista de TI

In [ ]:
# Exibe as linhas onde a coluna 'Cargo' contém 'Analista de Tecnologia da Informação'
analistas_ti_obj = df_resposta_obj[df_resposta_obj['Ocupação'].str.contains('ANALISTA DE TECNOLOGIA DA INFORMACAO', na=False)]
analistas_ti_obj

,Código\rdo Cargo,Ocupação,Incrição,Nome do Candidato,Tipo_Prova,Nota_obj,Situação_obj,Ranking_obj
4,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338115090,JAILSON DURAES CORDEIRO,B,38,Aprovado,1
5,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338104384,ROBERTO MIRANDA TORGA,B,37,Aprovado,2
6,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338132606,GABRIEL HELENO GONCALVES DA SILVA,A,37,Aprovado,3
7,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338111684,ALLAN AMANCIO MOREIRA SILVA,B,37,Aprovado,4
8,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338101820,THEOGENES FERREIRA DUARTE,D,36,Aprovado,5
...,...,...,...,...,...,...,...,...
253,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338105952,ADRIANO SILVA BORGES,D,25,Aprovado,242
254,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338112064,DOUGLAS CONRADO VIEIRA GUIMARAES SANTOS,B,25,Aprovado,243
255,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338123711,EDNILTA MOREIRA DOS SANTOS,B,25,Aprovado,244
256,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338118065,MICHELLE CRISTINA HONORIO DE SOUZA,C,25,Aprovado,245
257,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338123369,VILMAR BISPO SILVA,B,25,Aprovado,246

#Mesclando notas de candidatos de TI para apresentar Nota Objetiva e Discursiva

In [ ]:
# Merge the DataFrames
analistas_ti_geral = pd.merge(analistas_ti_obj, aprovados_ti_disc, left_on='Incrição', right_on='Num de inscrição', how='left')
analistas_ti_geral

,Código\rdo Cargo,Ocupação,Incrição,Nome do Candidato,Tipo_Prova,Nota_obj,Situação_obj,Ranking_obj,Num de inscrição,Nome Candidato,Cargo,NPD,Situação
0,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338115090,JAILSON DURAES CORDEIRO,B,38,Aprovado,1,0338115090,JAILSON DURAES CORDEIRO,Analista de Tecnologia da Informação,"17,03",Aprovado
1,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338104384,ROBERTO MIRANDA TORGA,B,37,Aprovado,2,0338104384,ROBERTO MIRANDA TORGA,Analista de Tecnologia da Informação,"13,58",Aprovado
2,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338132606,GABRIEL HELENO GONCALVES DA SILVA,A,37,Aprovado,3,0338132606,GABRIEL HELENO GONCALVES DA SILVA,Analista de Tecnologia da Informação,"13,93",Aprovado
3,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338111684,ALLAN AMANCIO MOREIRA SILVA,B,37,Aprovado,4,0338111684,ALLAN AMANCIO MOREIRA SILVA,Analista de Tecnologia da Informação,"14,17",Aprovado
4,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338101820,THEOGENES FERREIRA DUARTE,D,36,Aprovado,5,0338101820,THEOGENES FERREIRA DUARTE,Analista de Tecnologia da Informação,"11,66",Aprovado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338105952,ADRIANO SILVA BORGES,D,25,Aprovado,242,NaN,NaN,NaN,NaN,NaN
242,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338112064,DOUGLAS CONRADO VIEIRA GUIMARAES SANTOS,B,25,Aprovado,243,NaN,NaN,NaN,NaN,NaN
243,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338123711,EDNILTA MOREIRA DOS SANTOS,B,25,Aprovado,244,NaN,NaN,NaN,NaN,NaN
244,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338118065,MICHELLE CRISTINA HONORIO DE SOUZA,C,25,Aprovado,245,NaN,NaN,NaN,NaN,NaN
245,102.0,ANALISTA DE TECNOLOGIA DA INFORMACAO,0338123369,VILMAR BISPO SILVA,B,25,Aprovado,246,NaN,NaN,NaN,NaN,NaN

###Reduzindo dados para coletar apenas os necessários para análise

In [ ]:
resultado_geral_1 = analistas_ti_geral.drop(['Código\rdo Cargo', 'Ocupação', 'Tipo_Prova', 'Num de inscrição', 'Nome Candidato', 'Ocupação'], axis=1)
resultado_geral_1

,Incrição,Nome do Candidato,Nota_obj,Situação_obj,Ranking_obj,Cargo,NPD,Situação
0,0338115090,JAILSON DURAES CORDEIRO,38,Aprovado,1,Analista de Tecnologia da Informação,"17,03",Aprovado
1,0338104384,ROBERTO MIRANDA TORGA,37,Aprovado,2,Analista de Tecnologia da Informação,"13,58",Aprovado
2,0338132606,GABRIEL HELENO GONCALVES DA SILVA,37,Aprovado,3,Analista de Tecnologia da Informação,"13,93",Aprovado
3,0338111684,ALLAN AMANCIO MOREIRA SILVA,37,Aprovado,4,Analista de Tecnologia da Informação,"14,17",Aprovado
4,0338101820,THEOGENES FERREIRA DUARTE,36,Aprovado,5,Analista de Tecnologia da Informação,"11,66",Aprovado
...,...,...,...,...,...,...,...,...
241,0338105952,ADRIANO SILVA BORGES,25,Aprovado,242,NaN,NaN,NaN
242,0338112064,DOUGLAS CONRADO VIEIRA GUIMARAES SANTOS,25,Aprovado,243,NaN,NaN,NaN
243,0338123711,EDNILTA MOREIRA DOS SANTOS,25,Aprovado,244,NaN,NaN,NaN
244,0338118065,MICHELLE CRISTINA HONORIO DE SOUZA,25,Aprovado,245,NaN,NaN,NaN
245,0338123369,VILMAR BISPO SILVA,25,Aprovado,246,NaN,NaN,NaN

In [ ]:
# Remove rows where 'NPD' is null
resultado_geral_1 = resultado_geral_1.dropna(subset=['NPD'])
resultado_geral_1

,Incrição,Nome do Candidato,Nota_obj,Situação_obj,Ranking_obj,Cargo,NPD,Situação
0,0338115090,JAILSON DURAES CORDEIRO,38,Aprovado,1,Analista de Tecnologia da Informação,"17,03",Aprovado
1,0338104384,ROBERTO MIRANDA TORGA,37,Aprovado,2,Analista de Tecnologia da Informação,"13,58",Aprovado
2,0338132606,GABRIEL HELENO GONCALVES DA SILVA,37,Aprovado,3,Analista de Tecnologia da Informação,"13,93",Aprovado
3,0338111684,ALLAN AMANCIO MOREIRA SILVA,37,Aprovado,4,Analista de Tecnologia da Informação,"14,17",Aprovado
4,0338101820,THEOGENES FERREIRA DUARTE,36,Aprovado,5,Analista de Tecnologia da Informação,"11,66",Aprovado
...,...,...,...,...,...,...,...,...
181,0338109956,IALA PATRICIA DE JESUS MONTEIRO DE JESUS,26,Aprovado,182,Analista de Tecnologia da Informação,"13,27",Aprovado
190,0338127942,LUIZ FILIPE DE ALMEIDA RIBEIRO,26,Aprovado,191,Analista de Tecnologia da Informação,"13,62",Aprovado
194,0338127224,GEDAIAS ELOI BRANDAO,26,Aprovado,195,Analista de Tecnologia da Informação,"13,87",Aprovado
201,0338101433,DIEGO PEREIRA DA SILVA,26,Aprovado,202,Analista de Tecnologia da Informação,"11,84",Aprovado
211,0338118214,ANDRE LUIZ PEREIRA VALENTIM,26,Aprovado,212,Analista de Tecnologia da Informação,"11,04",Aprovado

In [ ]:
resultado_geral_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 211
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Incrição           99 non-null     object
 1   Nome do Candidato  99 non-null     object
 2   Nota_obj           99 non-null     object
 3   Situação_obj       99 non-null     object
 4   Ranking_obj        99 non-null     object
 5   Cargo              99 non-null     object
 6   NPD                99 non-null     object
 7   Situação           99 non-null     object
dtypes: object(8)
memory usage: 7.0+ KB

In [ ]:
resultado_geral_join = pd.DataFrame(resultado_geral_1)

# Convert 'NPD' and 'Nota_obj' columns to numeric, handling errors
resultado_geral_join['NPD'] = resultado_geral_1['NPD'].str.replace(',', '.').astype(float)
#resultado_geral_join['NPD'] = pd.to_numeric(resultado_geral_1['NPD'])
resultado_geral_join['Nota_obj'] = pd.to_numeric(resultado_geral_1['Nota_obj'], errors='coerce')

# Calculate 'Nota_Geral'
resultado_geral_join['Nota_Geral'] = resultado_geral_join['Nota_obj'] + resultado_geral_join['NPD']
resultado_geral_join

,Incrição,Nome do Candidato,Nota_obj,Situação_obj,Ranking_obj,Cargo,NPD,Situação,Nota_Geral
0,0338115090,JAILSON DURAES CORDEIRO,38,Aprovado,1,Analista de Tecnologia da Informação,17.03,Aprovado,55.03
1,0338104384,ROBERTO MIRANDA TORGA,37,Aprovado,2,Analista de Tecnologia da Informação,13.58,Aprovado,50.58
2,0338132606,GABRIEL HELENO GONCALVES DA SILVA,37,Aprovado,3,Analista de Tecnologia da Informação,13.93,Aprovado,50.93
3,0338111684,ALLAN AMANCIO MOREIRA SILVA,37,Aprovado,4,Analista de Tecnologia da Informação,14.17,Aprovado,51.17
4,0338101820,THEOGENES FERREIRA DUARTE,36,Aprovado,5,Analista de Tecnologia da Informação,11.66,Aprovado,47.66
...,...,...,...,...,...,...,...,...,...
181,0338109956,IALA PATRICIA DE JESUS MONTEIRO DE JESUS,26,Aprovado,182,Analista de Tecnologia da Informação,13.27,Aprovado,39.27
190,0338127942,LUIZ FILIPE DE ALMEIDA RIBEIRO,26,Aprovado,191,Analista de Tecnologia da Informação,13.62,Aprovado,39.62
194,0338127224,GEDAIAS ELOI BRANDAO,26,Aprovado,195,Analista de Tecnologia da Informação,13.87,Aprovado,39.87
201,0338101433,DIEGO PEREIRA DA SILVA,26,Aprovado,202,Analista de Tecnologia da Informação,11.84,Aprovado,37.84
211,0338118214,ANDRE LUIZ PEREIRA VALENTIM,26,Aprovado,212,Analista de Tecnologia da Informação,11.04,Aprovado,37.04

##Classificação final

In [ ]:
# prompt: Gere um resultado como classificação decrescente com base na  coluna 'Nota_Geral', apresentando apenas as colunas de 'Nome do Candidato', 'Nota_obj', 'NPD' e 'Nota_Geral', e acrescente a coluna de index apresentando em qual posição do ranking o candidato está

# Sort the DataFrame by 'Nota_Geral' in descending order
resultado_geral_join_sorted = resultado_geral_join.sort_values(by='Nota_Geral', ascending=False)

# Reset the index to create a rank column
resultado_geral_join_sorted = resultado_geral_join_sorted.reset_index(drop=True)

# Rename the index to 'Ranking'
resultado_geral_join_sorted.index.name = 'Ranking'

# Select the desired columns and display the result
resultado_final = resultado_geral_join_sorted[['Nome do Candidato', 'Nota_obj', 'NPD', 'Nota_Geral']]
resultado_final

                         Nome do Candidato  Nota_obj    NPD  Nota_Geral
Ranking
0                  JAILSON DURAES CORDEIRO        38  17.03       55.03
1              ALLAN AMANCIO MOREIRA SILVA        37  14.17       51.17
2               THALES ARAUJO CRONEMBERGER        35  16.10       51.10
3        GABRIEL HELENO GONCALVES DA SILVA        37  13.93       50.93
4                    FELIPE FREITAS SOARES        33  17.73       50.73
...                                    ...       ...    ...         ...
94               MARIANA APARECIDA PEREIRA        27  11.60       38.60
95                 ELIVAM DE SOUSA MARTINS        27  11.27       38.27
96              GUILHERME DE SOUZA PEREIRA        26  11.85       37.85
97                  DIEGO PEREIRA DA SILVA        26  11.84       37.84
98             ANDRE LUIZ PEREIRA VALENTIM        26  11.04       37.04

[99 rows x 4 columns]